install.packages("remotes")
install.packages("tidyverse")
install.packages("grid")
install.packages("gplots")
install.packages("gridExtra")
install.packages("pheatmap")
install.packages("matrixStats")
install.packages("doMC")
install.packages("umap")
install.packages("Matrix")
install.packages("princurve")
install.packages("vioplot")
install.packages("viridis")
install.packages("cowplot")
install.packages("patchwork")
install.packages("ggrastr")
install.packages("ggplotify")
install.packages("ggforce")
install.packages("gridExtra")

if (!require("BiocManager", quietly = TRUE)){install.packages("BiocManager")}'
BiocManager::install(version = "3.20")'

remotes::install_github("tanaylab/tgstat")
remotes::install_github("tanaylab/tglkmeans")
BiocManager::install("tanaylab/metacell")
BiocManager::install("ComplexHeatmap")
BiocManager::install("sparseMatrixStats")
BiocManager::install("Gviz")
remotes::install_github("tanaylab/metacell.flow")
remotes::install_github("tanaylab/misha")
remotes::install_github("tanaylab/misha.ext")
remotes::install_github("tanaylab/shaman")
remotes::install_github("tanaylab/mcATAC")
remotes::install_github("tanaylab/iceqream")

